version: 3
silent: true
tasks:
  default:
    desc: Show all tasks
    cmd: task -a

  install:
    desc: Install dependencies
    cmds:
      - fnm install --corepack-enabled && fnm use
      - corepack enable pnpm
      - pnpm i
      - pnpx playwright install chromium #--with-deps
      - sudo apt install graphicsmagick ghostscript -y

  run:
    desc: Run development server
    cmd: pnpm dev

  # Sometimes git is not tracking the files that are in .gitignore
  # This task will fix that
  # See: https://stackoverflow.com/questions/25436312/gitignore-not-working
  fix_gitignore:
    desc: Fix git not tracking files in .gitignore
    cmds:
      - git rm -rf --cached .
      - git add .

  test:
    desc: Run tests
    cmds:
      - pnpm test

  update:
    desc: Update dependencies
    cmds:
      - pnpm update
      - pnpx playwright install chromium #--with-deps

  clean:
    desc: Clean project
    cmds:
      - rm -rf .pnpm-store node_modules test-results .next out pnpm-lock.yaml
      - rm -rf `find . -type d -name temp`
      - pnpm store prune
      - echo "Project cleaned successfully 🙀"

  build:
    desc: Build project
    cmd: pnpm build
