version: 3
silent: true
tasks:
  default:
    desc: Show all tasks
    cmd: task -a

  install:
    desc: Install dependencies
    cmd: pnpm i

  storybook:
    desc: Run storybook
    cmd: pnpm storybook
  run:
    desc: Run development server
    cmd: pnpm dev

  lint:
    desc: Lint code
    cmd: pnpm lint
