version: "3"
tasks:
  dev:
    desc: Start development server
    cmds:
      - pnpm dev

  install:
    desc: Install dependencies
    cmds:
      - task: disable_telemetry
      - pnpm install

  build:
    desc: Build for production
    cmds:
      - pnpm build

  # update_search_index:
  #   desc: Generate search index
  #   cmds:
  #     - pnpm update:search-meta

  prune:
    desc: Prune dependencies and clean repo
    cmds:
      - rm -rf .next next-env.d.ts node_modules
      - pnpm prune

  disable_telemetry:
    desc: Disable telemetry
    cmds:
      - pnpm exec next telemetry disable
