version: "3"
tasks:
  dev:
    desc: Start development server
    cmds:
      - pnpm dev

  install:
    desc: Install dependencies
    cmds:
      - pnpm install

  build:
    desc: Build for production
    cmds:
      - pnpm build

  disable_telemetry:
    desc: Disable nextjs telemetry
    cmds:
      - pnpm exec next telemetry disable

  # Sometimes git is not tracking the files that are in .gitignore
  # This task will fix that
  # See: https://stackoverflow.com/questions/25436312/gitignore-not-working
  fix_gitignore:
    desc: Fix gitignore
    cmds:
      - git rm -rf --cached .
      - git add .
