version: 3

tasks:
  default:
    silent: true
    cmds:
      - task -l

  install:
    desc: Install dependencies
    cmds:
      - yarn install

  start:
    desc: Start complete website
    cmds:
      - yarn start

  ########
  ## For mobile platforms
  ########
  app:merge-pdf:build:
    desc: Build merge pdf app
    cmds:
      - cd apps/merge-pdf && npx docusaurus build
      - git-bash -c "cp package.json apps/merge-pdf/package.json"
      - cd apps/merge-pdf && npx cap sync android
      - git-bash -c "rm -r apps/merge-pdf/package.json"

  app:merge-pdf:start:
    desc: Start merge pdf app in development mode
    cmds:
      - cd apps/merge-pdf && npx docusaurus start

  app:merge-pdf:sync:
    desc: Start merge pdf app in development mode
    cmds:
      - cd apps/merge-pdf && npx docusaurus start

  android:run:
    desc: Launch android app
    cmds:
      - task: app:merge-pdf:build
      - cd apps/merge-pdf && npx cap run android
