version: 3

tasks:
  default:
    silent: true
    cmds:
      - task -l

  install:
    desc: Install dependencies
    cmds:
      - yarn install

  start:
    desc: Start complete website
    cmds:
      - yarn start

  ########
  ## For mobile platforms
  ########
  app:merge-pdf:build:
    desc: Build merge pdf app
    cmds:
      - cd apps/merge-pdf && npx docusaurus build

  app:merge-pdf:start:
    desc: Start merge pdf app in development mode
    cmds:
      - cd apps/merge-pdf && npx docusaurus start
