FROM mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm

# RUN apt-get update && apt-get upgrade -y
# RUN apt-get install -y xvfb
# RUN apt-get install -qqy x11-apps

# # chromium dependencies
# RUN apt-get install -y libnss3 \
#                        libxss1 \
#                        libasound2 \
#                        fonts-noto-color-emoji