import { dateToday } from "./date";
import { makeid } from "./id";

//#####################
//# General Constants
//#####################
export const SPLASH_BACKGROUND_COLOR = "#000b18";
export const BACKGROUND_COLOR = "#16181a";
export const SELECTED_BORDER_COLOR = "deepskyblue";

//#####################
//# PDF Constants
//#####################
export const PDF_FILENAME_PREFIX = dateToday + "-";
export const PDF_FILENAME_MIDDLE = makeid(5);
export const PDF_FILENAME_SUFFIX = "";
export const PDF_FILENAME =
  PDF_FILENAME_PREFIX + PDF_FILENAME_MIDDLE + PDF_FILENAME_SUFFIX;

//#####################
//# Image Constants
//#####################
export const IMAGE_FILENAME_PREFIX = "image_";
export const IMAGE_FILENAME_MIDDLE = makeid(5);
export const IMAGE_FILENAME_SUFFIX = "_avtoolz";
export const IMAGE_FILENAME =
  IMAGE_FILENAME_PREFIX + IMAGE_FILENAME_MIDDLE + IMAGE_FILENAME_SUFFIX;
export const IMAGE_EXTENSIONS = [
  ".ase",
  ".art",
  ".bmp",
  ".blp",
  ".cd5",
  ".cit",
  ".cpt",
  ".cr2",
  ".cut",
  ".dds",
  ".dib",
  ".djvu",
  ".egt",
  ".exif",
  ".gif",
  ".gpl",
  ".grf",
  ".icns",
  ".ico",
  ".iff",
  ".jng",
  ".jpeg",
  ".jpg",
  ".jfif",
  ".jp2",
  ".jps",
  ".lbm",
  ".max",
  ".miff",
  ".mng",
  ".msp",
  ".nef",
  ".nitf",
  ".ota",
  ".pbm",
  ".pc1",
  ".pc2",
  ".pc3",
  ".pcf",
  ".pcx",
  ".pdn",
  ".pgm",
  ".PI1",
  ".PI2",
  ".PI3",
  ".pict",
  ".pct",
  ".pnm",
  ".pns",
  ".ppm",
  ".psb",
  ".psd",
  ".pdd",
  ".psp",
  ".px",
  ".pxm",
  ".pxr",
  ".qfx",
  ".raw",
  ".rle",
  ".sct",
  ".sgi",
  ".rgb",
  ".int",
  ".bw",
  ".tga",
  ".tiff",
  ".tif",
  ".vtf",
  ".xbm",
  ".xcf",
  ".xpm",
  ".3dv",
  ".amf",
  ".ai",
  ".awg",
  ".cgm",
  ".cdr",
  ".cmx",
  ".dxf",
  ".e2d",
  ".egt",
  ".eps",
  ".fs",
  ".gbr",
  ".odg",
  ".svg",
  ".stl",
  ".vrml",
  ".x3d",
  ".sxd",
  ".v2d",
  ".vnd",
  ".wmf",
  ".emf",
  ".art",
  ".xar",
  ".png",
  ".webp",
  ".jxr",
  ".hdp",
  ".wdp",
  ".cur",
  ".ecw",
  ".iff",
  ".lbm",
  ".liff",
  ".nrrd",
  ".pam",
  ".pcx",
  ".pgf",
  ".sgi",
  ".rgb",
  ".rgba",
  ".bw",
  ".int",
  ".inta",
  ".sid",
  ".ras",
  ".sun",
  ".tga",
  ".heic",
  ".heif",
];
