default_platform(:android)

platform :android do
  # desc "Deploy a beta version to the Google Play"
  # lane :beta do
  #   gradle(
  #   task: "clean bundleRelease",
  #   properties: {
  #     "android.injected.signing.store.file" => ENV['KEYSTORE_PATH'],
  #     "android.injected.signing.store.password" => ENV['STORE_PASSWORD'],
  #     "android.injected.signing.key.alias" => ENV['KEY_ALIAS'],
  #     "android.injected.signing.key.password" => ENV['KEY_PASSWORD'],
  #     "org.gradle.java.home" => ENV['JAVA_HOME']
  #   }
  # )
  #   upload_to_play_store(track: 'beta')
  # end
  desc "Deploy a new version to the Google Play"
    lane :production do
    setup_ci if ENV['CI']
    
    # Increment Build number
    previous_build_number = google_play_track_version_codes(
        package_name: ENV['APP_ID'],
        track: "production",
        json_key: ENV['JSON_KEY_PATH'],
      )[0]
    current_build_number = previous_build_number + 1
    increment_version_code(
        version_code: current_build_number
      )
    
    # Commit the changes to origin
    gitpush  
    
    # Build app bundle
    gradle(
    task: "clean bundleRelease",
    properties: {
      "android.injected.signing.store.file" => ENV['KEYSTORE_PATH'],
      "android.injected.signing.store.password" => ENV['STORE_PASSWORD'],
      "android.injected.signing.key.alias" => ENV['KEY_ALIAS'],
      "android.injected.signing.key.password" => ENV['KEY_PASSWORD'],
      "org.gradle.java.home" => ENV['JAVA_HOME']
    })

    # Publish app bundle to play store
    upload_to_play_store(json_key: ENV['PLAY_STORE_JSON_KEY_PATH'], track: 'production')

    end
  
end

lane :buildlocal do
  gradle(
    task: "clean bundleRelease",
    properties: {
      "android.injected.signing.store.file" => ENV['KEYSTORE_PATH'],
      "android.injected.signing.store.password" => ENV['STORE_PASSWORD'],
      "android.injected.signing.key.alias" => ENV['KEY_ALIAS'],
      "android.injected.signing.key.password" => ENV['KEY_PASSWORD'],
      "org.gradle.java.home" => ENV['JAVA_HOME']
    }
  )
end



lane :gitpush do
  sh("git config --global user.email 'av@7hell.ml'")  
  sh("git config --global user.name 'aV'")
  git_add
  git_commit(path: "*", message: "PDF Merger X Version Bump")
  push_to_git_remote
end