name: Release merge-pdf (PDF Merger X) to Playstore

on:
  workflow_dispatch:
  # push:
  #   paths:
  #     - "app/**"
  #   branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0" # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Cache Ruby - Bundler
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Cache Gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches/
          key: cache-clean-gradle-${{ matrix.os }}-${{ matrix.jdk }}

      - name: Cache Gradle Wrapper
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper/
          key: cache-clean-wrapper-${{ matrix.os }}-${{ matrix.jdk }}

      - name: Grant Permission to Execute
        run: |
          chmod +x apps/merge-pdf/android/gradlew

      - name: Install bundle
        run: |
          cd apps/merge-pdf/android
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Install Task
        uses: arduino/setup-task@v1

      - name: Distribute app to Production 🚀
        run: task app:merge-pdf:release
